fix the docker setup
zenaton/examples-php pull request #15
Opened 2019-08-02 15:49 UTC by antoinereyt

# CHANGES:

The `.env` file is now optional.

If it not exists, environment variables will be used.

This allows you to use `.env` in local to ease development. 

And for deploy, where you do not want to put credentials in the image, you can use environment variables.

This will ease a lot the deploy on Cloud environments.

2019-08-02 16:00 UTC, jalric approved these changes

2019-08-07 16:23 UTC, MrYawe requested changes

2019-08-07 16:23 UTC, MrYawe commented on docker-compose.yml
> +      - .env
Missing EOL 😄

2019-08-07 16:25 UTC, antoinereyt commented on docker-compose.yml
> +      - .env
fixed ;-)

2019-08-08 08:25 UTC, MrYawe approved these changes

2019-08-09 10:16 UTC, pylebecq approved these changes
👏

2019-08-09 10:16 UTC, pylebecq commented on Dockerfile
>  ADD composer.json composer.lock ./
I think we can take the opportunity to also change this last `ADD` to a `COPY`. Should work exactly the same.

2019-08-09 10:19 UTC, merged